### ISSUE TITLE
Crashes after screen wakeup on Ubuntu 19.10

### ISSUE THREAD

**Issue by loxK** [hardpixel/unite-shell#174] opened 2020-04-30 07:46 UTC
I get this error:

```
JS ERROR: Extension unite@hardpixel.eu: Error: Argument 'actor' (type interface) may not be null
                                           init/Clutter.Actor.prototype.toString@resource:///org/gnome/shell/ui/environment.js:243:16
                                           registerHandler@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:54:20
                                           connect@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:71:12
                                           _init@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:337:7
                                           _init@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:13:28
                                           enable@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:39:18
                                           _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:149:13
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:281:21
                                           callback@resource:///org/gnome/shell/ui/extensionDownloader.js:244:17
                                           gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:108:13

```

**Comment by jonian** [comment] 2020-04-30 19:53
Hi @loxK, thanks for the report. Have you tried with the master branch? Also is this on wayland, xorg or both?

**Comment by loxK** [comment] 2020-05-03 23:43
I didn't try master and it is on xorg

**Comment by loxK** [comment] 2020-05-07 01:35
More information. It works on boot but then crashes when waking up the screen. Restarting Gnome Shell doesn't help, uninstalling, reinstalling doesn't either.

This is maybe related ? https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/228

**Comment by jonian** [comment] 2020-05-07 10:17
Try replacing in `handlers.js` file in `registerHandler` function:

```js
// Replace this line
const key = `${object}[${name}]`

// With these
const uid = Math.random().toString(36).substr(2, 9)
const key = `${uid}-${name}`
```

Please report back if the issue is fixed.

**Comment by loxK** [comment] 2020-05-09 01:02
Made the change, rebooted, locked the screen and the extension is still active on login in.
It seems fixed. Thks!

**Comment by loxK** [comment] 2020-05-09 04:00
Damn it crashed again and I don't find any occurrence of 'unite' in the shell logs ...

**Comment by loxK** [comment] 2020-05-13 22:50
I have applied the fix but it still crashes sometimes:
```

JS ERROR: Extension unite@hardpixel.eu: Error: Argument 'instance' (type interface) may not be null
                                        disconnect@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:77:7
                                        disconnectAll@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:89:7
                                        destroy@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:451:7
                                        destroy@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:31:7
                                        disable@/home/lox/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:44:3

gnome-software[12733]: unite_hardpixel.eu has error: Error: Argument 'instance' (type interface) may not be null
```

**Comment by loxK** [comment] 2020-05-15 02:38
It happens when the screen goes black, not on session lock/unlock

**Comment by loxK** [comment] 2020-05-27 05:19
This may be related, or not ... You tell me https://bugzilla.gnome.org/show_bug.cgi?id=781760

**Comment by jonian** [comment] 2021-02-05 11:31
Closing as I can't reproduce this issue. If it is still present please open a new issue with fresh logs.

**Closed by jonian** 2021-02-05 11:31 UTC
Labels: bug, not reproducible
