### ISSUE TITLE
Hiding window controls on maximized windows with headerbars not working in 20.04

### ISSUE THREAD

**Issue by lekseven** [hardpixel/unite-shell#176] opened 2020-04-30 20:28 UTC
Control buttons in titlebars are not hidden when windows are maximized.

![Screenshot from 2020-04-30 23-26-21](https://user-images.githubusercontent.com/2146480/80755855-36160c00-8b3a-11ea-9037-f2e1ea248870.png)

**Comment by wxq851685279** [comment] 2020-05-01 12:44
Same problem

**Comment by Hoking007** [comment] 2020-05-03 07:11
Same problem

**Comment by Valeryan24** [comment] 2020-05-04 18:41
I don't want to open a new issue because of this and #173 : I have the same bug, but only on Firefox on Ubuntu 20.04, window buttons still visible in maximized state.

But for all other programs - Thunderbird or even those with headerbar - it's OK...

**Comment by lekseven** [comment] 2020-05-04 19:08
@Valeryan24 Did you upgrade from 18.04 or do a clean install of 20.04?

**Comment by Valeryan24** [comment] 2020-05-04 20:37
Hi, I upgraded from Ubuntu 19.10 on the early stage of development version of 20.04, then did the updates until the final release.

Only today I installed GS extension Unite - before I had many others (now removed) to do the same.

And Firefox is the beta version from Firefox-Next ppa...

For all other programs tested it works well, only FF I also have the buttons on the Menu bar - enabled.

**Comment by jonian** [comment] 2020-05-04 20:48
@Valeryan24 If you have disabled titlebar from firefox customize screen, you will have duplicate buttons. The extension cannot remove CSD (client side decorations) buttons from non GTK applications.

When #82 is implemented, you will be able to hide the panel buttons for individual applications.

**Comment by jonian** [comment] 2020-05-04 20:52
@lekseven I can't reproduce this issue, can you post the output of `cat ~/.config/gtk-3.0/gtk.css` and `journalctl /usr/bin/gnome-shell | grep unite`?

**Comment by Valeryan24** [comment] 2020-05-04 22:00
valeryan24@valeryan24-desktop:~$ cat ~/.config/gtk-3.0/gtk.css
/* UNITE windowDecorations */
@import url('/home/valeryan24/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-left/maximized.css');
/* windowDecorations UNITE */

`valeryan24@valeryan24-desktop:~$ journalctl /usr/bin/gnome-shell | grep unite
valeryan24@valeryan24-desktop:~$ `

**Comment by jonian** [comment] 2020-05-05 10:16
@Valeryan24, as I said in my previous comment, that is not a bug. It is something that unite **can't do**.

For client side decorated (CSD) GTK applications, unite uses CSS styles to hide the decorations. 

Firefox is not a GTK app, so unite can't hide the decorations. If you don't want to see duplicate window controls, enable "Title Bar" if Firefox customize screen.

**Comment by Valeryan24** [comment] 2020-05-05 11:16
@jonian Sorry, I misread and thought the question was for me...

Yes you're right, with Title bar enabled and Firefox restarted, I don't see anymore the buttons and the title bar is well merged on the top panel - perfect, thanks !

**Comment by jonian** [comment] 2020-05-05 22:18
@Valeryan24 If you want to make firefox CSD titlebar buttons to hide when maximized you can add in `~/.mozilla/firefox/yourprofile/chrome/userChrome.css`:

```css
#main-window[sizemode="maximized"] .titlebar-buttonbox-container  {
  display: none !important;
}
```

Maybe I will add this in the readme.

**Comment by lekseven** [comment] 2020-05-07 21:05
@jonian 
```
$ cat ~/.config/gtk-3.0/gtk.css

@import url('/home/lekseven/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-left.css');
```
```
$ journalctl /usr/bin/gnome-shell | grep unite

...
enable@/home/lekseven/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:52:20
_createButtons@/home/lekseven/.local/share/gnome-shell/extensions/unite@hardpixel.eu/modules/windowButtons.js:84:21
_onActivate@/home/lekseven/.local/share/gnome-shell/extensions/unite@hardpixel.eu/modules/windowButtons.js:39:10
_runCallback@/home/lekseven/.local/share/gnome-shell/extensions/unite@hardpixel.eu/module.js:41:17
_activate@/home/lekseven/.local/share/gnome-shell/extensions/unite@hardpixel.eu/module.js:46:12
_init@/home/lekseven/.local/share/gnome-shell/extensions/unite@hardpixel.eu/module.js:19:10
_init@/home/lekseven/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:25:30
```

**Comment by lekseven** [comment] 2020-05-07 21:07
Another example of the issue:

![Screenshot from 2020-05-08 00-06-18](https://user-images.githubusercontent.com/2146480/81344636-d4b4e680-90bf-11ea-87f0-e13d8e9e56a6.png)

**Comment by jonian** [comment] 2020-05-08 01:34
@lekseven, you are using an old version. Please update to latest version.

**Closed** 2020-05-08 07:57 UTC
