### ISSUE TITLE
Missing close button for maximized windows on secondary monitor

### ISSUE THREAD

**Issue by peterzeller** [hardpixel/unite-shell#142] opened 2019-11-04 23:34 UTC
Applications with integrated window buttons like Files or Terminal loose the buttons when maximized on the secondary screen:
![image](https://user-images.githubusercontent.com/6633573/68166557-fd1e2580-ff62-11e9-8649-4acf797ed176.png)

On my primary screen the buttons are displayed correctly in the top bar: 
![image](https://user-images.githubusercontent.com/6633573/68166690-69992480-ff63-11e9-9103-182775688434.png)

It would be nice if I could have the same behavior on both screens, i.e. show the bar at the top with close-buttons, clock, volume control, etc.

My settings:

![image](https://user-images.githubusercontent.com/6633573/68166648-45d5de80-ff63-11e9-9b2d-57aae8c41527.png)

![image](https://user-images.githubusercontent.com/6633573/68166630-3787c280-ff63-11e9-9188-f45918f8c8c7.png)

**Comment by jonian** [comment] 2020-01-02 10:02
Duplicate of #148

**Closed by jonian** 2020-01-02 10:02 UTC
