### ISSUE TITLE
[Feature request] Ability to put window buttons somewhere else in the top bar.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [hardpixel/unite-shell#88] opened 2019-01-11 17:27 UTC
Fe. to the left of the system tray or of the date and time. I think I'd prefer the first one.

Right now, I accidently turn off Firefox because I'm used to GNOME controls being the last icons on the top bar.

**Comment by yechs** [comment] 2019-04-18 13:13
FYI, if you change the Window Titlebar's Placement setting to `left` in Gnome Tweaks, the buttons will appear on the left of the top bar.

The problem is, the buttons will be between the applications and title, which is weird
![image](https://user-images.githubusercontent.com/49149993/56363391-a6761780-61db-11e9-9d03-c7af4bb638db.png)

**Comment by jonian** [comment] 2019-04-18 14:50
@yechs This feature request will be implemented but there is no timeline. If you want to give it a try, PRs are welcome.

Similar requests are issues #41 and #52.

**Comment by jonian** [comment] 2019-10-03 08:49
Duplicate of #41

**Closed by jonian** 2019-10-03 08:49 UTC
Labels: feature

**Comment by jonian** [comment] 2019-10-03 17:35
Commi https://github.com/hardpixel/unite-shell/commit/cc7604df98ad77283713e4a2473b5245754f2677 add buttons position options:

- auto
- left (before appMenu)
- right (before aggregateMenu, fixes @gerg5c42g542g2c54g52c issue)
- first (fixes @yechs isssue)
- last
