### ISSUE TITLE
[Feature Request] Blacklist/Whitelist for global window buttons

### ISSUE THREAD

**Issue by Motor-head** [hardpixel/unite-shell#287] opened 2022-03-19 19:28 UTC
As of Unite version 59, running on Gnome 41.3, there is no per application Whitelist/Blacklist for window buttons (Minimize, Maximize, Close). All the maximized windows show Window buttons on topbar, despite having their own buttons built-in (Firefox, Chromium, etc).

![Screenshot from 2022-03-20 01-00-22](https://user-images.githubusercontent.com/93347209/159135687-144f9955-f9c4-46a4-98b7-7c11f732b8e0.png)

**Comment by jonian** [comment] 2022-03-19 19:31
Duplicate of #82

**Closed by jonian** 2022-03-19 19:31 UTC
