### ISSUE TITLE
High CPU usage when "Show system tray in top bar" is active

### ISSUE THREAD

**Issue by prurigro** [hardpixel/unite-shell#96] opened 2019-03-21 18:03 UTC
The `gnome-shell` process consistently uses about 40-60% CPU when `Show system tray in top bar` is enabled, and drops down to ~4% when disabled.

This is with v27 and gnome 3.32.

Cheers!

**Comment by jonian** [comment] 2019-03-21 19:26
As mentioned in issue #53:

This is a known bug in gnome shell:
https://gitlab.gnome.org/GNOME/gnome-shell/issues/1054

A solution is to use the app-indicators extension and keep `tray icons` disabled:
https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by jonian** [comment] 2019-03-21 19:27
Closing, since this is not an bug caused by this extension.

**Closed by jonian** 2019-03-21 19:27 UTC
Labels: invalid

**Comment by arooni** [comment] 2019-03-21 20:15
> A solution is to use the app-indicators extension and keep `tray icons` disabled:
> https://github.com/ubuntu/gnome-shell-extension-appindicator

So I tried to install this extension today on 18.04 but just got an error message.

**Comment by Nicolab** [comment] 2019-04-17 22:11
May be from https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by jeroenpraat** [comment] 2019-06-09 14:57
Maybe an idea to temporary disable the systray support, until the upstream bug is solved.
