### ISSUE TITLE
[Bug] Removing title bar in maximized mode creates sharp corners in the window later.

### ISSUE THREAD

**Issue by fcaballerop** [hardpixel/unite-shell#215] opened 2020-11-29 17:48 UTC
This only happens to some applications, but if removing titlebars when maximized, after minimazing, sharp corners appears in the new titlebar. See pictures, done with the atom editor, as a program that does this:

When opening program:
![before](https://user-images.githubusercontent.com/18356029/100549453-54302000-3273-11eb-951f-c59843facdef.png)

Maximizing, so that buttons go into the gnome top panel:
![maximized](https://user-images.githubusercontent.com/18356029/100549463-5db98800-3273-11eb-969f-ba8a089df130.png)

Back to window mode:
![after](https://user-images.githubusercontent.com/18356029/100549474-67db8680-3273-11eb-8918-0db5b16921b9.png)

**Comment by jonian** [comment] 2021-01-06 14:51
Duplicate of #120

**Closed by jonian** 2021-01-06 14:51 UTC
