### ISSUE TITLE
Systray icons slightly larger in hidpi screen

### ISSUE THREAD

**Issue by memeplex** [hardpixel/unite-shell#149] opened 2019-11-26 06:15 UTC
I have a 3000x2000 screen and use a 2x scaling factor. Systray icons look slightly larger than other icons in the top bar.

![image](https://user-images.githubusercontent.com/2845433/69603969-e10a2300-0ffa-11ea-90b9-4aea25854929.png)

Maybe a control to fine tune icon size would be a solution.

**Comment by jonian** [comment] 2020-01-02 10:03
Duplicate of #141

**Closed by jonian** 2020-01-02 10:03 UTC
