### ISSUE TITLE
Incorrect restore button while maximized

### ISSUE THREAD

**Issue by manuelrazola** [hardpixel/unite-shell#241] opened 2021-04-30 09:44 UTC
Restore button while maximized is incorrect, as if it wasn't already maximized.
What should we expect:
![image](https://user-images.githubusercontent.com/48353543/116677987-1c0b4580-a9a9-11eb-987c-f3547a6622b0.png)
Current Restore Image:
![image](https://user-images.githubusercontent.com/48353543/116678013-23325380-a9a9-11eb-928d-e9d3938f9471.png)

**Comment by jonian** [comment] 2021-09-15 18:43
Duplicate of #165

**Closed by jonian** 2021-09-15 18:43 UTC
