### ISSUE TITLE
Not working well with Places Status Indicator

### ISSUE THREAD

**Issue by yoyoys** [hardpixel/unite-shell#121] opened 2019-06-25 17:22 UTC
![image](https://user-images.githubusercontent.com/22124891/60119291-a896bc80-97b0-11e9-9d44-99fa932143d7.png)
`Places Status Indicator` force add menu at top left, and looks so embarrassing.

**Comment by jonian** [comment] 2019-06-25 17:27
Duplicate of #88

**Closed by jonian** 2019-06-25 17:27 UTC
