### ISSUE TITLE
Flickering or tearing when back from lock screen

### ISSUE THREAD

**Issue by StarryTony** [hardpixel/unite-shell#226] opened 2021-02-08 19:24 UTC
Hi, thanks for your work. 
I fond this great extension on gnome extensions website. It works quite good with dash to panel. But only one terrible issue, if the computer wakes up from sleep or lock screen, graphics are flickering or tearing and the whole screen is not readable. I have to disable it and reboot to get the graphics restored.

My setup: NVIDIA proprietary driver (GeForce GTX 1070 Mobile) + Wayland + GNOME 3.38.3 + GDM on ArchLinux 5.10.13-arch1-1. All updated to the latest version.

**Comment by jonian** [comment] 2021-09-15 18:34
Closing because I can't reproduce this.

**Closed by jonian** 2021-09-15 18:34 UTC
