### ISSUE TITLE
Multiple buttons in Fullscreen

### ISSUE THREAD

**Issue by steviehs** [hardpixel/unite-shell#57] opened 2018-08-24 07:02 UTC
After Running the Desktop for some time (days? dunno), I get multiple buttons on top:
![grafik](https://user-images.githubusercontent.com/26877141/44569940-4cbc6b00-a77c-11e8-837f-36d2f91c16b2.png)
Restarting gnome shell get's back to the normal behavior.

**Comment by jonian** [comment] 2018-08-26 08:37
Hi @steviehs. Can you test the latest master branch? I think the issue is fixed.

**Comment by ysolis** [comment] 2018-08-30 16:19
if is fixed in the master branch ... do we are going need to wait that the update get released in gnome extensions page ?

**Comment by jonian** [comment] 2018-08-30 16:33
@ysolis Thanks for the report.

No, you do not have to wait for the gnome extensions page release. You can edit metadata.json and add `"18"` as value to the `version` [key](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/metadata.json#L7), or you can keep using the master branch if you want. Adding the value to the version key will allow the extension to be updated when a new version is released in gnome extensions page.

If you are on Arch Linux (Manjaro, Antergos) you can use the [AUR package](https://aur.archlinux.org/packages/gnome-shell-extension-unite).

**Closed by jonian** 2018-08-30 16:33 UTC
Labels: bug
