### ISSUE TITLE
Error, when trying to uphgreade/install from https://extensions.gnome.org/extension/1287/unite/

### ISSUE THREAD

**Issue by jringoot** [hardpixel/unite-shell#258] opened 2021-09-28 05:34 UTC
Error, when trying to upgrade from https://extensions.gnome.org/extension/1287/unite/
![Screenshot from 2021-09-28 07-32-41](https://user-images.githubusercontent.com/2686933/135028965-b817fb5f-f4ba-44f2-a8aa-d8889b1bfb59.png)

I suspect this might be related to a recent upgrade from debian 10 to 11
Uninstall/reinstall of the plugin gives the same result

**Comment by jonian** [comment] 2021-09-28 06:36
Hi @jringoot, please check https://github.com/hardpixel/unite-shell/issues/225#issuecomment-807061349.

Duplicate of #225

**Closed by jonian** 2021-09-28 06:36 UTC

**Comment by jringoot** [comment] 2021-09-29 13:05
it was resolved after another computer reboot. (I read some people just had to log out and in again)
