### ISSUE TITLE
tittlebar issue with firefox

### ISSUE THREAD

**Issue by fikrillah** [hardpixel/unite-shell#105] opened 2019-04-14 05:55 UTC
there's option in firefox to disable tittle bar, which is working great when this extension disabled. but when the extension activated. there's always title bar on firefox when not maximized, which is unwanted. so please make an exception to firefox and other similar behaviour app...

here's firefox when not maximized
![Screenshot from 2019-04-14 12-48-30](https://user-images.githubusercontent.com/48489341/56088889-bb893880-5eb3-11e9-8e25-6b4e978d4b78.png)

firefox without extension
![Screenshot from 2019-04-14 12-53-22](https://user-images.githubusercontent.com/48489341/56088925-5aae3000-5eb4-11e9-8177-a31767a57876.png)

**Comment by jonian** [comment] 2019-04-14 06:58
Has already been fixed. Update to latest version.

Duplicate of #93

**Closed by jonian** 2019-04-14 06:58 UTC
