### ISSUE TITLE
Today's update broke this extension

### ISSUE THREAD

**Issue by Obscure-Git** [hardpixel/unite-shell#293] opened 2022-04-25 12:08 UTC
Todays update has broken this extension in Ubuntu 20.04,

now when I install it, it shows shows error.

**Comment by jonian** [comment] 2022-04-25 12:14
Hi @Obscure-Git, thanks for the report. Please provide the output of `journalctl -g unite`. Before releasing the new version, I tested in a Ubuntu 20.04 VM and it works fine.

**Comment by Obscure-Git** [comment] 2022-04-26 13:13
```
-- Logs begin at Fri 2022-04-15 09:38:39 +0545, end at Tue 2022-04-26 18:57:59 +0545. --
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/settings.ui
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/panel.js
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/layout.js
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/helper.js
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/prefs.js
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/window.js
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/spacing-classic.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/spacing-legacy.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/org.gnome.shell.extensions.unite>
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/gschemas.compiled
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/both.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/always.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/maximized.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/tiled.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/both.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/always.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/maximized.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/tiled.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/both.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/always.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/maximized.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/tiled.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/both.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/always.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/maximized.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/tiled.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/shell/
Apr 15 18:21:32 Obscure gnome-shell[157368]:   inflating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/shell/spacing.css
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/themes/
Apr 15 18:21:32 Obscure gnome-shell[157368]:    creating: /home/obscure/.local/share/gnome-shell/extensions/unite@hardpixel.eu/themes/dracula/

```

**Comment by jonian** [comment] 2022-04-27 00:36
There is no error in your logs. Have you tried log out and log in again? Is the extension enabled?

**Comment by Obscure-Git** [comment] 2022-04-27 10:27
I have updated the extension and then logged out and in and yes the extension is enabled. I have rebooted as well. Still keeps showing the red "ERROR" button in the extensions page and the extension doesnt work. 

Meanwhile i have manually added the v64 plugin rn from releases tab and using it which works fine

**Comment by jonian** [comment] 2022-04-27 19:49
Since there are no errors in your log and I can't reproduce this issue I'm closing it. Generally you should not update extensions from extensions website, they update themselves when you restart your session. Check this [comment](https://github.com/hardpixel/unite-shell/issues/225#issuecomment-807061349) for more details.

**Closed by jonian** 2022-04-27 19:49 UTC
