### ISSUE TITLE
Unite extensions causes immediate log-out after login

### ISSUE THREAD

**Issue by pyoor** [hardpixel/unite-shell#83] opened 2018-12-04 16:57 UTC
After the recent update, Unite shell extension causes X to automatically log out after log in.

**Comment by pyoor** [comment] 2018-12-04 17:04
From the gnome-shell journal:

Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: **
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: Gjs:ERROR:gi/object.cpp:2024:void gjs_define_object_class(JSContext*, JS::HandleObject, GIObjectInfo*, GType, JS::Mutabl
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: == Stack trace for context 0x55adb840c4c0 ==
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #0 0x7ffc1a896540 b   resource:///org/gnome/gjs/modules/_legacy.js:531 (0x7fa88debd4d8 @ 363)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #1 0x7ffc1a8965a0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa88deb5de0 @ 71)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #2 0x7ffc1a896650 b   resource:///org/gnome/gjs/modules/_legacy.js:114 (0x7fa88deb5f78 @ 178)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #3 0x7ffc1a896720 b   resource:///org/gnome/gjs/modules/_legacy.js:65 (0x7fa88deb5cd0 @ 152)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #4 0x55adb8900840 i   /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu/convenience.js:7 (0x7fa8666
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #5 0x55adb89007a8 i   /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:3 (0x7fa8666148
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #6 0x55adb8900710 i   /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu/module.js:3 (0x7fa8666143c8
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #7 0x55adb8900678 i   /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu/modules/activateWindow.js:4
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #8 0x55adb89005e0 i   /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:4 (0x7fa866608
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #9 0x55adb8900508 i   resource:///org/gnome/shell/ui/extensionSystem.js:231 (0x7fa88da5a450 @ 214)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #10 0x55adb8900470 i   resource:///org/gnome/shell/ui/extensionSystem.js:168 (0x7fa88da5a2b8 @ 182)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #11 0x55adb89003f0 i   resource:///org/gnome/shell/ui/extensionSystem.js:318 (0x7fa88da5a9a0 @ 13)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #12 0x7ffc1a89cba0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fa88ded2230 @ 386)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #13 0x55adb8900310 i   resource:///org/gnome/shell/misc/extensionUtils.js:191 (0x7fa88da5e120 @ 459)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #14 0x7ffc1a89d810 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa88deb5de0 @ 71)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #15 0x55adb8900280 i   resource:///org/gnome/shell/misc/extensionUtils.js:197 (0x7fa88da5e230 @ 28)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #16 0x7ffc1a89e510 b   resource:///org/gnome/shell/misc/fileUtils.js:27 (0x7fa88da5e340 @ 323)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #17 0x55adb89001f0 i   resource:///org/gnome/shell/misc/extensionUtils.js:196 (0x7fa88da5e1a8 @ 72)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #18 0x7ffc1a89f170 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa88deb5de0 @ 71)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #19 0x55adb8900160 i   resource:///org/gnome/shell/ui/extensionSystem.js:320 (0x7fa88da5a918 @ 201)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #20 0x55adb89000e0 i   resource:///org/gnome/shell/ui/extensionSystem.js:328 (0x7fa88da5aa28 @ 36)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #21 0x55adb8900060 i   resource:///org/gnome/shell/ui/extensionSystem.js:359 (0x7fa88da5ac48 @ 67)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #22 0x55adb88fffd8 i   resource:///org/gnome/shell/ui/extensionSystem.js:367 (0x7fa88da5acd0 @ 41)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #23 0x55adb88fff48 i   resource:///org/gnome/shell/ui/main.js:229 (0x7fa88deda340 @ 1152)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #24 0x55adb88ffec0 i   resource:///org/gnome/shell/ui/main.js:133 (0x7fa88deda230 @ 237)
Dec 04 11:46:40 xps org.gnome.Shell.desktop[2918]: #25 0x55adb88ffe48 i   <main>:1 (0x7fa88de86b38 @ 48)

**Comment by pyoor** [comment] 2018-12-04 17:06
See also:
https://askubuntu.com/questions/1098336/gnome-on-ubuntu-18-04-is-crashing-after-logging-in

**Comment by jdittrich** [comment] 2018-12-04 19:17
I had the same problem. The askubuntu suggests to delete the files. You could also [disable the extension](https://askubuntu.com/questions/1098336/gnome-on-ubuntu-18-04-is-crashing-after-logging-in/1098468#1098468)

**Comment by jonian** [comment] 2018-12-04 19:19
Duplicate of #76

**Comment by jonian** [comment] 2018-12-04 19:20
This issue has been resolved. Install latest version from [here](https://github.com/hardpixel/unite-shell/releases/download/v24/unite-shell-v24.zip).

**Closed by jonian** 2018-12-04 19:20 UTC
