### ISSUE TITLE
[Feature Request] Reorder elements on the menubar

### ISSUE THREAD

**Issue by arooni** [hardpixel/unite-shell#52] opened 2018-05-30 20:03 UTC
Love this, it's the only thing that makes using ubuntu 18.04 feel 'right'.  Thank you.

I'm wondering if there could be a way to reorder elements on the menubar.  would be really nice.  I tried to use https://extensions.gnome.org/extension/1201/extend-panel-menu/ but it breaks your extension.

**Comment by jonian** [comment] 2019-10-03 08:49
Duplicate of #41

**Closed by jonian** 2019-10-03 08:49 UTC
Labels: feature, help wanted
