### ISSUE TITLE
Ubuntu 23.10

### ISSUE THREAD

**Issue by AlwynBarry** [hardpixel/unite-shell#341] opened 2023-09-27 15:01 UTC
**Describe the bug**
Under Ubuntu 23.10 Unite is broken.  The error is `import declarations may only appear at top level of a module`.

**To Reproduce**
1. Install Ubuntu 23.10
2. Login
3. Unite isn't operating - see the error using the Extension Manager app.

**Expected behavior**
Unite starts up

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04] Ubuntu 23.10
 - GNOME Shell version [e.g. 42] 45
 - Unite version [e.g. 65] 72

**Logs**
Provide system logs related to unite extension using `journalctl -g unite`.
JS ERROR: Could not load extension unite@hardpixel.eu: Error: Failed>
                                                   createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem>
                                                   _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:>
                                                   collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:28>
                                                   _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:61>
                                                   _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.>
                                                   _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:66>
                                                   init@resource:///org/gnome/shell/ui/extensionSystem.js:58:14
                                                   _initializeUI@resource:///org/gnome/shell/ui/main.js:319:22
                                                   start@resource:///org/gnome/shell/ui/main.js:196:5
                                                   @resource:///org/gnome/shell/ui/init.js:6:17

**Additional context**
The errors come because the code still uses the 'old' style imports.  The Extension Manager App reports the first exception as in prefs.js and there are module imports there which are 'old' style.  The way to update them for Gnome Shell 45 is given here:
[https://gjs.guide/extensions/upgrading/gnome-shell-45.html](https://gjs.guide/extensions/upgrading/gnome-shell-45.html)

I guess there could be other Gnome Shell 45 changes that will cause other errors.

**Comment by jonian** [comment] 2023-10-01 13:58
Duplicate of #339

**Closed by jonian** 2023-10-01 13:58 UTC
