### ISSUE TITLE
Make the clock position better

### ISSUE THREAD

**Issue by TROMsite** [hardpixel/unite-shell#70] opened 2018-11-19 22:32 UTC
I would suggest to do something about the clock position because it can be lost between the other icons like in my case: 
![2018-11-19_23-29](https://user-images.githubusercontent.com/38043315/48739132-4b072400-ec53-11e8-98c3-7bf0ea2f0c25.png)

Maybe add a space between the clock and the other elements, or a bar separating it, or move it to the right edge. That would be helpful. Thanks for your work!

**Comment by jonian** [comment] 2018-12-02 00:57
Hi @TROMsite, thank you for your input. This is a duplicate of issue #41.

**Closed by jonian** 2018-12-02 00:57 UTC
