### ISSUE TITLE
Window buttons break top panel layout

### ISSUE THREAD

**Issue by pokebadgerswithspoon** [hardpixel/unite-shell#100] opened 2019-03-26 11:28 UTC
Env:
- hidpi screen with 200% scale
- gnome 3.32
- unite v 27

Changing "Top bar window buttons theme" nor gnome shell theme helps

### No buttons
Note that texts and buttons are  is in the middle of the top bar

![image](https://user-images.githubusercontent.com/6481705/54993456-df531000-4fd2-11e9-806f-80030ea9e14c.png)

### With buttons
"Vertex" theme for buttons is used, but it does not matter.
Note how bottom padding is different from top padding

![image](https://user-images.githubusercontent.com/6481705/54993513-04e01980-4fd3-11e9-9691-92d981897669.png)

**Comment by jonian** [comment] 2019-03-26 17:33
@pokebadgerswithspoon thanks for the report. 

The latest version applies your system fonts to the shell theme. Can you try to change system font to `Cantarell` to see if it makes any difference.

**Comment by pokebadgerswithspoon** [comment] 2019-03-26 20:50
Looks better with `Cantarell` but whole the issue is definitly there. Enabling/disabling unite triggers vertical jump for the icons

![image](https://user-images.githubusercontent.com/6481705/55032241-878fc580-5021-11e9-9f08-d7f1215cd70a.png)

**Comment by jonian** [comment] 2019-04-10 20:17
@pokebadgerswithspoon Can you try the master branch that has an option to disable inheriting system fonts? Please report back if the issue is fixed. Thanks.

**Comment by pokebadgerswithspoon** [comment] 2019-04-13 12:04
@jonian no luck, it looks the same.

Dunno if screenshots of any help, but still here they are.

## Enabled

#### OSX

![image](https://user-images.githubusercontent.com/6481705/56079380-4a3a7e80-5dfc-11e9-8899-3492edebccf2.png)

#### Vertex

![image](https://user-images.githubusercontent.com/6481705/56079388-6a6a3d80-5dfc-11e9-9787-290f1e97133d.png)

## Disabled

![image](https://user-images.githubusercontent.com/6481705/56079406-a30a1700-5dfc-11e9-9027-b8eb736ed2ea.png)

**Comment by pokebadgerswithspoon** [comment] 2019-04-13 13:13
Playing with version 29-1 (AUR). Check these screenshots. When unite is enabled "Activities" and central parts become bigger. And right part pulled down. 

# Disabled

![image](https://user-images.githubusercontent.com/6481705/56080219-a2767e00-5e06-11e9-9910-c26b8b54bb50.png)

# Enabled

![image](https://user-images.githubusercontent.com/6481705/56080223-b0c49a00-5e06-11e9-8421-0ec92877791a.png)

**Comment by jonian** [comment] 2019-04-13 15:28
Do you use a custom gnome-shell theme or the default? I can't reproduce this with the default theme.

**Comment by pokebadgerswithspoon** [comment] 2019-04-13 15:30
default
but i'm on rolling release with everything fresh, what is your setup? (gnome version and themes) I could try to roll back to it and if it looks okey then apply updates to find out when it breaks
![image](https://user-images.githubusercontent.com/6481705/56081791-f63e9280-5e19-11e9-8615-e722ac791e40.png)

**Comment by jonian** [comment] 2019-04-13 15:40
I'm on Arch Linux too, so we have the same system. Maybe it is an issue with the hidpi sreen.

Can you try changing https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/stylesheet.css#L44 as shown below:

```scss
// From this
#panel .window-buttons-box .window-button {
  width: 22px;
  height: 28px;
}

// To this
#panel .window-buttons-box .window-button {
  width: 22px;
  height: 100%;
}
```

**Comment by pokebadgerswithspoon** [comment] 2019-04-13 15:54
Thats way better, thanks!
I dont know how to record only top line in a screencast, accept my apologies for 4k gif.
Here is what does it look like with suggested update
http://www.webmshare.com/play/nYoVr

**Comment by jonian** [comment] 2019-04-13 15:59
Thanks for testing. Can you also test with all the button themes to see if there is an issue?

For easier testing set "Show window buttons in top bar" to "Always" and use the mouse wheel to scroll through the themes.

**Comment by jonian** [comment] 2019-04-14 06:59
Closing since it is fixed in master branch.

**Closed by jonian** 2019-04-14 06:59 UTC
Labels: bug

**Comment by pokebadgerswithspoon** [comment] 2019-04-16 09:19
Sorry for late report.
https://webmshare.com/PaRZx
a screencast of diffrent button themes being applied to unite.
You may notice slight shift on some (way better than it used to be).
It does not matter if "Topicons" extension is enabled, nor  "Apply system fonts to shell theme".
