### ISSUE TITLE
not working for ubuntu terminal title bar

### ISSUE THREAD

**Issue by kaykhancheckpoint** [hardpixel/unite-shell#269] opened 2021-10-28 15:01 UTC
this does not seem to be working for ubuntu terminal title bar,

![image](https://user-images.githubusercontent.com/65535942/139283000-2d792329-3690-4eaf-8dbd-0f624d4ae8f6.png)

**Comment by jonian** [comment] 2021-11-01 09:24
Hi @kaykhancheckpoint, is your terminal app installed as a snap/flatpak? The extension does not support apps installed with snap/flatpak.

**Comment by kaykhancheckpoint** [comment] 2021-11-01 09:29
Its the default ubuntu terminal

**Comment by jonian** [comment] 2021-11-01 09:31
So is it installed with snap/flatpak? You can check with `snap list` for gnome-terminal.

**Comment by kaykhancheckpoint** [comment] 2021-11-02 11:23
i cant see gnome-terminal in either of those

```snap list                                 
Name               Version             Rev    Tracking         Publisher     Notes
bare               1.0                 5      latest/stable    canonical✓    base
code               6cba118a            78     latest/stable    vscode✓       classic
core               16-2.52.1           11993  latest/stable    canonical✓    core
core18             20211015            2246   latest/stable    canonical✓    base
gnome-3-34-1804    0+git.3556cb3       72     latest/stable/…  canonical✓    -
gtk-common-themes  0.1-59-g7bca6ae     1519   latest/stable/…  canonical✓    -
nvim               v0.5.0-dirty        1395   latest/beta      neovim-snap   classic
postman            8.12.5              149    v8/stable        postman-inc✓  -
robo3t-snap        v1.3.1              4      latest/stable    shalev67      -
slack              4.20.0              46     latest/stable    slack✓        classic
snap-store         3.38.0-64-g23c4c77  547    latest/stable/…  canonical✓    -
snapd              2.52.1              13640  latest/stable    canonical✓    snapd

 flatpak list
command not found: flatpak

**Comment by RomainClem** [comment] 2021-11-10 16:24
I'm having the same issue, using gnome terminal on Ubuntu 20.04.3 LTS.

**Comment by jonian** [comment] 2022-03-20 11:48
Can't reproduce. Closing. If anyone can reproduce and fix it, please submit a PR.

**Closed by jonian** 2022-03-20 11:48 UTC
