### ISSUE TITLE
Changing Scaling doesn't refresh window control buttons in top bar

### ISSUE THREAD

**Issue by Goddard** [hardpixel/unite-shell#318] opened 2023-01-03 18:16 UTC
If you change the scale from say 200% to 100% the buttons in the top menu bar remain at 200%.  Some how if possible this change needs to be detected and redraw at the correct scale.

**Comment by jonian** [comment] 2023-02-05 23:13
Duplicate of #106

**Closed by jonian** 2023-02-05 23:13 UTC
