### ISSUE TITLE
Extension can't hide window title bar and move wondow buttons to top bar

### ISSUE THREAD

**Issue by sedighi66** [hardpixel/unite-shell#188] opened 2020-07-24 08:50 UTC
Hi there,
First of all, I should mention that this extension is great. Thank you.
The problem is when a new window has moved to another workspace or minimized for any reason, then unite can't hide the window title bar and move the buttons to the top bar. For example, when I active Auto move window extension and it moves my windows to another workspace, it happens. Or when I open another project in Android Studio and it minimizes that, it happens.
I use Ubuntu 20.04 LTS in Xorg.

**Comment by jonian** [comment] 2020-08-29 14:34
Hi @sedighi66, sorry for the super late response. I have reproduced this issue and will try to provide a fix soonish.

**Comment by jonian** [comment] 2020-08-29 14:38
Duplicate of #173

**Closed** 2020-08-29 14:38 UTC
Labels: bug
