### ISSUE TITLE
Telegram title bar don't hide in fullscreen mode

### ISSUE THREAD

**Issue by dziaineka** [hardpixel/unite-shell#200] opened 2020-09-20 09:11 UTC
![image](https://user-images.githubusercontent.com/2579623/93707660-35a5fe00-fb39-11ea-9650-e3500b4bc1f5.png)

Fedora 32
Wayland
[Telegram](https://www.rpmfind.net/linux/RPM/rpmfusion/free/fedora/updates/32/x86_64/t/telegram-desktop-2.3.2-1.fc32.x86_64.html)

The same thing with Kvantum Manager:
![image](https://user-images.githubusercontent.com/2579623/93707785-22476280-fb3a-11ea-968d-6428686180fc.png)

Thank you for such great extension!

**Comment by jonian** [comment] 2020-09-24 18:02
Hi @dziaineka, thanks for the report. Open a terminal, type `xprop`, click on Kvantum/Telegram window and provide the output.

Regarding telegram, the latest version uses CSD (client side decorations) and you have to disable them for unite to work. More info here https://www.omgubuntu.co.uk/2020/07/telegram-desktop-system-window-frame.

**Comment by dziaineka** [comment] 2020-09-24 18:42
@jonian it seems that xprop doesn't work for wayland apps. No output in terminal :(

**Comment by jonian** [comment] 2020-09-24 18:50
Unite supports only GTK wayland apps. This is a known issue. Please see issue #167 for a workaround.

**Comment by jonian** [comment] 2020-09-24 18:50
Duplicate of #167

**Closed by jonian** 2020-09-24 18:50 UTC

**Comment by gcvl** [comment] 2022-09-24 16:18
@jonian Hi! Maybe I should file a new bug about this, but anyway...
This wasn't happening before: I'm on the latest Unite 67, Ubuntu 22.04 and if you right-click a message and then dismiss the popup by clicking on the background, the Telegram maximized window's titlebar comes back with duplicate buttons.
[Video del 24-09-2022 18:17:00.webm](https://user-images.githubusercontent.com/29081089/192108308-df9ebdd6-33a4-4cc4-b5c5-878e24d1a481.webm)

**Comment by jonian** [comment] 2022-09-24 16:35
@gcvl thanks for the report. Yes, you should open a new issue for this. I can replicate this on arch linux.
