### ISSUE TITLE
Everything works EXCEPT hide window titlebars

### ISSUE THREAD

**Issue by xindekai** [hardpixel/unite-shell#298] opened 2022-06-04 12:01 UTC
firstly, this extension is perfect for my requirements, thank you for the effort etc...
as the title says I have the extension installed and working, everything functions perfectly (eg hide Activities, buttons in bar etc...), except for the big feature: title bar hiding. My titlebars just sit there mocking me with their fat pixel greediness on all settings (Always, max, tile, both).
Fedora 36
Gnome 42.2
Unite extension version 65.
Any help on either getting it working or finding out why it's not would be greatly appreciated.
Thank you for your time.

**Comment by jonian** [comment] 2022-06-04 12:05
Hi @xindekai, thanks for the report. You should have used issue template to provide all answers, like the system logs, Do you have `xprop` installed? Please provide the unite logs.

**Comment by xindekai** [comment] 2022-06-06 09:29
sorry for not following the template, I am way too stupid to be doing any of this...
xprop 1.2.3 installed. (`xprop -version`)
logs... 
journalctl -g unite is just filled with a bunch of inflating/deflating timestamps on fedora gnome-shell. It's weird there are hundreds of them all with the exact same time stamp to the second... BUT there is one other entry in there:
`Could not create transient scope for PID:0 GDBus.error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-org.gnome.Extensions-0.scope already exists`
This text is in yellow.
Other logs... beyond my competency I am sorry to say.
Thank you for your time and assistance.

**Comment by jonian** [comment] 2022-06-06 09:39
The inflating/deflating log entries are from the installation of the extension. The entry you have provided is not for unite. It looks like there are no errors related to extension.

Can you try to remove the decorations manually? Type in a terminal:

```
xprop -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2 0x0 0x2 0x0 0x0"
```

It will show a crosshair pointer. Click on the window you want to remove the decorations.

**Comment by xindekai** [comment] 2022-06-06 09:43
no crosshair pointer: terminal hangs needs ctrl-C

**Comment by xindekai** [comment] 2022-06-06 09:50
ok, is xprop not working in general or just in this particular instance? I am not sure what it is or does and only installed it because I wanted your extension...

**Comment by jonian** [comment] 2022-06-06 19:20
Xprop works on wayland for xwayland apps. For native wayland apps, unite uses css to hide the decorations and only gtk apps are supported (not flatpaks, snaps).

I'm closing this issue since it is not a bug/error of the extension.

**Closed by jonian** 2022-06-06 19:20 UTC
