### ISSUE TITLE
Spacing of the icons squeezed after lock screen

### ISSUE THREAD

**Issue by SPYFF** [hardpixel/unite-shell#240] opened 2021-04-23 08:13 UTC
Hi! When my machine boots up, the spacing between the icons looks fine. However when I lock the screen then unlock it, the spacing between the system icons squeezed a little bit. I attached a screenshot from this phenomenon.

![](https://i.imgur.com/jSJ8T3w.png)

This happens with the 9c2d023e8d1c68324b9cdd570b317c38416ad352 version.

**Comment by jonian** [comment] 2021-04-23 08:49
Hi @SPYFF, thanks for the report. Please provide the output of the following:

```sh
gnome-shell --version
journalctl -g unite
```

**Comment by SPYFF** [comment] 2021-04-23 09:02
```
gnome-shell --version
GNOME Shell 3.38.4
```

```
journalctl -g unite
-- Journal begins at Sun 2020-11-01 10:17:18 CET, ends at Fri 2021-04-23 11:01:01 CEST. --
nov 01 10:17:22 pc gnome-shell[1069]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
nov 01 17:31:07 pc gnome-shell[29424]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 4d5d96189c494f92a633478df6ff69e7 --
nov 02 11:40:47 pc gnome-shell[1068]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot dc074982986a4ebfbce860d38f8232d8 --
nov 02 19:37:50 pc gnome-shell[1067]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot eda7bc3918c340fd9d590096966f6858 --
nov 03 11:10:12 pc gnome-shell[1092]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
nov 03 16:58:01 pc gnome-shell[27568]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 579cc13e20f249e4bec464308be92fb5 --
nov 04 11:30:52 pc gnome-shell[1096]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 0219e40ceeb94af9bec26a914206487f --
-- Boot c41e4ee3197e4929b289530845103ec8 --
nov 04 17:02:08 pc gnome-shell[1089]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 93b9d3434a7c433b8d2f860ad5e161e9 --
nov 05 12:05:51 pc gnome-shell[1093]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 4738993cfd854ac6adaf4e4c26a43f17 --
nov 05 11:22:03 pc gnome-shell[1015]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
nov 05 11:31:25 pc gnome-shell[3870]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 95090c642bdb45329d9f2dc58922a689 --
nov 05 14:45:12 pc gnome-shell[1011]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 5f214171327b4f4e93856c7524f6524c --
nov 05 19:07:32 pc gnome-shell[996]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot ffc45298184f45a6b7f9d502069de7ee --
nov 06 10:05:17 pc gnome-shell[994]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
nov 06 10:06:43 pc gnome-shell[2169]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 7a0fd5b34d434170a8179024e04bf98f --
nov 07 10:19:26 pc gnome-shell[1025]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 9ad78b79bcdd472ebde776bba3fe21e0 --
nov 08 11:04:43 pc gnome-shell[997]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 7bee5795689b4d3ba1548ef82bbe630f --
nov 08 20:09:11 pc gnome-shell[970]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 80a55007186b4d2a95f875e443b1196a --
nov 08 21:29:06 pc gnome-shell[992]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot f4b7847cab6d401fa89d8301b4bd51f5 --
nov 09 08:25:00 pc gnome-shell[998]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot be85db78acc0479b8b426364d00a89a3 --
nov 10 11:59:18 pc gnome-shell[1030]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 87299d88dc5e41479ede34893c05b043 --
nov 11 08:34:18 pc gnome-shell[1023]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot a058e6277f2c42c79f4b32c3e146f22c --
nov 11 17:09:36 pc gnome-shell[983]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 55da65708c084fbabbf9b3ab2bbc6996 --
nov 12 09:19:38 pc gnome-shell[977]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 2d0de00ac0cb47b284847493c5cceec0 --
nov 13 08:37:15 pc gnome-shell[1004]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot a0d85707829d4cf8a91ca4b50714ad02 --
nov 14 11:01:51 pc gnome-shell[974]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 111bdb84b3f94e6394a9f1a6af952381 --
nov 14 15:34:01 pc gnome-shell[974]: Extension [0;1;31mFailed to get MESSAGE field: Bad message
1munite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot 3a3ce931d4a647528497f40e84b6396d --
nov 15 11:06:41 pc gnome-shell[972]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
nov 15 12:51:55 pc gnome-shell[11195]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
-- Boot d16526fa2795467c8efede7a48a06f66 --
nov 15 18:35:13 pc gnome-shell[988]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
nov 15 20:57:05 pc gnome-shell[13804]: Extension unite@hardpixel.eu already installed in /home/user/.local/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
```

**Comment by SPYFF** [comment] 2021-04-23 16:50
Its on Manjaro linux, so the gnome package version is 40, same as in the about menu at the settings (which tells Gnome 40).

**Comment by jonian** [comment] 2021-04-23 17:27
I can't reproduce this on arch linux with gnome shell 40. Maybe it is a theme issue. Have you tried to reproduce it with the default theme?

**Comment by SPYFF** [comment] 2021-04-23 17:45
Thanks for looking into it! Same happens with the default theme too. If its ok with the gnome-shell 40 I think the best if I wait until the Manjaro's package updating to that version, not a big issue after all

**Comment by jonian** [comment] 2021-04-23 17:55
Closing for now. If the issue persists after you get the latest update we can reopen it.

**Closed by jonian** 2021-04-23 17:55 UTC

**Comment by SPYFF** [comment] 2021-07-13 20:59
Manjaro updated its Gnome version since then and I can confirm that this issue is solved with that. There are few pixel inconsistencies in the spacing but looks much better.
