### ISSUE TITLE
Move Menubars into the Gnome-bar.

### ISSUE THREAD

**Issue by heschy2** [hardpixel/unite-shell#297] opened 2022-05-28 13:58 UTC
**Describe the solution you'd like**
I would like to move the Menubars to the Top Bar of gnome. Just like its done in unity.

**Describe alternatives you've considered**
It could also be packed into a pop-up menu, like the appmenu. 

**Screenshot**
I have a screenshot of the Menubar from Nemo, the Topbar, and the App-menu.
![Bildschirmfoto vom 2022-05-28 15-50-36](https://user-images.githubusercontent.com/105609148/170828566-94b7724e-4275-4242-ae12-99903a291d3d.png)

**Comment by jonian** [comment] 2022-06-07 06:41
Duplicate of #67

**Closed by jonian** 2022-06-07 06:41 UTC
