### ISSUE TITLE
Login crash in later versions of extension

### ISSUE THREAD

**Issue by Skeletonxf** [hardpixel/unite-shell#153] opened 2020-01-17 18:09 UTC
I got an update that my version of unite was out of date so I tried to update it but this immediately caused my system to crash and then I got stuck in an endless login loop. I managed to fix the login loop by disabling this extension and then tried reinstalling older versions to find where the crash was introduced.

I have downgraded to version 32 of the extension on gnome shell 3.32.0 on Ubuntu 19.04 which is not resulting in crashes, however versions 34 and 35 both stop me from logging in when I try to use those - I presume they are crashing gnome? I haven't tried version 33.

**Comment by jonian** [comment] 2020-01-17 18:12
Hi @Skeletonxf, thanks for the report. Please provide the output of `journalctl /usr/bin/gnome-shell | grep unite`.

**Comment by Skeletonxf** [comment] 2020-01-17 18:37
```
Jan 17 17:57:56 skeletonxf gnome-shell[2246]: Theme parsing error: gtk.css:2:121: Failed to import: Error opening file /home/skeletonxf/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-left/maximized.css: No such file or directory
```

The actual layout of `styles` is:
```
styles
├── buttons-left-always.css
├── buttons-left.css
├── buttons-left-tiled.css
├── buttons-right-always.css
├── buttons-right.css
└── buttons-right-tiled.css
```

in versions 32 and 34.

I notice the directory layout you have in master and version 35 reflects the path to the file the error has?

**Comment by jonian** [comment] 2020-01-17 21:14
The issue is fixed in v36. You can download it from github releases or wait for the update from gnome shell extensions.

**Closed by jonian** 2020-01-17 21:14 UTC
