### ISSUE TITLE
Unite can not hide window title bar (some time) + work around

### ISSUE THREAD

**Issue by secondstriker** [hardpixel/unite-shell#193] opened 2020-08-27 09:55 UTC
Some time this extension can't hide the window title bar. The recorded video explains everything. I copied the extension folder from the Github repository.

https://drive.google.com/file/d/15hGWVhZv9BdLEGmTMQDRK5p8OJpS1uNr/view?usp=sharing

**Comment by jonian** [comment] 2020-08-29 14:10
Hi @secondstriker, thanks for the report. Could you, please, provide a link to the video that does not require login?

**Comment by Orycteropus** [comment] 2020-09-02 06:47
Same issue here. As a workaround I restart gnome shell using alt+f2 -> r.
The only bug I encountered with Ubuntu 20.04, except that, the plugin works like a charm.

**Comment by jonian** [comment] 2020-09-02 07:05
@Orycteropus what exactly is the issue? I can't see the video submitted by @secondstriker because it is not public.

**Comment by jonian** [comment] 2020-09-02 07:07
If the issue is the same as #173 (compatibility with "Auto move windows" extension), it has already been fixed in master.

**Comment by Orycteropus** [comment] 2020-09-02 07:53
Auto move is disabled on my system. 

I will try to make you a video of the issue when it will occur the next time (it already appeared one time today).

As far as I'm concern, sometimes, when I open an application, the top bar is not hidden when I maximise it. I didn't notice any specific pattern that can explain that. I will try to be more vigilent to give you the more informations I can.

**Comment by jonian** [comment] 2020-09-02 07:56
@Orycteropus please use the master branch for your tests, the issue might have already been fixed. Thanks!

**Comment by Orycteropus** [comment] 2020-09-02 08:02
Ok, I just installed the master, i'll let you know if the problem still continues to occur. Thank you.

**Comment by secondstriker** [comment] 2020-09-03 11:52
> Hi @secondstriker, thanks for the report. Could you, please, provide a link to the video that does not require login?

It is now available. Sorry for checking late.

**Comment by secondstriker** [comment] 2020-09-03 11:55
> If the issue is the same as #173 (compatibility with "Auto move windows" extension), it has already been fixed in master.

No, it is not related to that extension. I don't have it.

**Comment by Orycteropus** [comment] 2020-09-03 13:58
Just to let you know that since I used the extension from the master, the issue didn't appeared again. Is it possible for you @secondstriker to test it too ?

**Comment by secondstriker** [comment] 2020-09-04 05:08
> Just to let you know that since I'm using the version of the master, the problem doesn't appear anymore. Is it possible for you @secondstriker to test it too ?

I copied the updated extension folder from the master branch. It seems the problem is resolved. As I mentioned before, the problem sometimes had happened. But so far so good with the updated extension.

**Comment by jonian** [comment] 2020-09-04 08:44
@secondstriker, @Orycteropus thanks for helping resolve the issue. I will close this. If it occurs again, we can re-open it.

**Closed by jonian** 2020-09-04 08:44 UTC
