### ISSUE TITLE
Option to truncate the title to a fixed length

### ISSUE THREAD

**Issue by smalltimer** [hardpixel/unite-shell#197] opened 2020-09-10 22:41 UTC
Hi, 

I think the option to truncate the title to a fixed length (in number of characters or in pixels) might be very handy in some setups. Right now, long titles tend to run through the date/time in the centre.  

Cheers!

**Comment by jonian** [comment] 2020-09-11 14:14
Duplicate of #80

**Closed by jonian** 2020-09-11 14:14 UTC
