### ISSUE TITLE
Add a blocklist for windows/apps/extensions

### ISSUE THREAD

**Issue by 3pical** [hardpixel/unite-shell#309] opened 2022-09-27 18:03 UTC
Unite picks up the Desktop Icons NG (DING) extension and gives it window buttons despite it not needing window buttons. This problem only exists on wayland, however this could be solved by adding a blocklist.

**Comment by jonian** [comment] 2022-09-27 18:05
Duplicate of #302 and already fixed.

**Closed by jonian** 2022-09-27 18:05 UTC

**Comment by 3pical** [comment] 2022-09-27 19:29
The solution is just to turn off DING :/

**Comment by jonian** [comment] 2022-09-27 19:30
@3pical the issue has been fixed but there is no release yet. If you want you can use the master branch or wait for a new release.
