### ISSUE TITLE
Tray icon problems

### ISSUE THREAD

**Issue by barkap** [hardpixel/unite-shell#171] opened 2020-04-25 11:02 UTC
![unite-icon-problem](https://user-images.githubusercontent.com/1485739/80278023-c0eea500-86fb-11ea-9578-bb6e8c401fef.png)

Icons: Nextcloud, Dropbox, Telegram, HexChat, QOwnNotes, Flameshot, Micorosft Teams, Discrod

I saw https://github.com/hardpixel/unite-shell/issues/160, it was closed with no comments, same problem with the latest version (v40 with default settings). Mostly Qt applications are affected (discoloration and white background) although there are some other icons with different heights as well.

gnome-shell-extension-unite 40 (arch aur package)
Manjaro 20.0
GNOME 3.36.1
HiDPI display on Wayland (same bug on Xorg)
All other extensions disabled

**Comment by skluthe** [comment] 2020-04-29 15:30
I'm experiencing this with Barrier as well. A temporary solution until this is fixed would be allowing us to hide icons we don't want shown.

**Comment by jonian** [comment] 2020-04-30 01:14
Hi @barkap, I cant reproduce this on Arch Linux (I don't have a HiDPI display to test). Try disabling all other extensions and use default gnome theme and icon theme.

Hi @skluthe, I do not intend do add such feature. I you want to implement it, I will happily accept a PR.

**Comment by skluthe** [comment] 2020-04-30 01:27
Unfortunately I'm not familiar with how this is put together but I'll take
a look at it and see if I can do it and submit a pull request. Can you try
using the base Manjaro Gnome install? That should reproduce it quite easily
for you.

**Comment by jonian** [comment] 2020-04-30 01:39
@skluthe, I'm very busy with work related projects, so I don't have the time to setup a VM now, sorry. 

Have you tested with other top-icons extensions? Do they have the same problem? 

Also, unite does not render the tray icons, they are rendered by gnome-shell as you can see [here](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/panel.js#L411).

**Comment by skluthe** [comment] 2020-04-30 02:28
I definitely hear you on the work thing. I'll try out some different
themes/add-ons/etc. To see what the issue might be.

**Comment by tiotrom** [comment] 2020-05-02 17:56
This is how icons look on my Manjaro with https://extensions.gnome.org/extension/1031/topicons/ installed 
![image](https://user-images.githubusercontent.com/34804533/80871742-48b15200-8cae-11ea-983a-ae4ee2dfa37e.png)
And this is how they look with the Unite extension:
![image](https://user-images.githubusercontent.com/34804533/80871862-a5ad0800-8cae-11ea-9cd1-0b6cf17514fa.png)
I am using greyscale for both. 

In Unite the icons are very crowded despite not having the "reduce top bar icons spacing" active. I'd say Unite should add more space between the icons and for the greyscale it should improve how it does it. For instance in TopIcons I have set the following for better visibility:

![image](https://user-images.githubusercontent.com/34804533/80871924-f7ee2900-8cae-11ea-972a-c255a09e14a1.png)

Maybe if you could add some controls over the icons (size, color, space) would help solve such issues.
Thanks!

**Comment by jonian** [comment] 2020-05-02 21:00
@tiotrom, thanks for the screenshots. Re rendering of the icons is the same in both extensions except unite has hard-coded settings for desaturation: 1.0 brightness: 0.2 contrast: 0.3.

**Comment by tiotrom** [comment] 2020-05-02 22:44
Maybe if you can tweak those values so the icons look more naturally. They look a bit washed out. Also, the space between them could be improved I'd say.

**Comment by barkap** [comment] 2020-05-03 19:54
I did some testing in a virtual environment and this is what I found out:
1) You are right @jonian, icons indeed are rendering as expected on clean Arch Linux with Gnome and with unite-shell extension enabled;
2) By default Manjaro installs some extensions and these are enabled right after installation:
* Dash to Dock
* KStatusNotifierItem/AppIndicator Support
* Pamac Updates Indicator
* User Themes

If all these extensions are disabled and only unite is upgraded+enabled, icons are messed up (like in my original screenshot). However, if (re)enable KStatusNotifierItem/AppIndicator extension then icons are ok.

So while I cannot say where the problem is, a solution to this problem is to enable KStatusNotifierItem extension along with unite-shell. Not really a fix I think, but works for me.

**Comment by skluthe** [comment] 2020-05-03 19:59
Works for me too. Thanks!

**Comment by tiotrom** [comment] 2020-05-04 15:27
I can confirm on a fresh install of TROMjaro (for example), the top icons are messed up like the OP says. Basically if you only install Unite on a Gnome desktop environment, then the tray icons are messed up. It works fine with other similar extensions that enable the tray icons. I hope the developer finds the mighty bug :D.

**Comment by jonian** [comment] 2021-09-15 18:32
Closing as I have not been able to reproduce this.

**Closed by jonian** 2021-09-15 18:32 UTC
Labels: help wanted, not reproducible
