### ISSUE TITLE
Black empty space when starting LibreOffice without menu bar

### ISSUE THREAD

**Issue by LostinSpacetime** [hardpixel/unite-shell#233] opened 2021-04-01 08:13 UTC
When I use the Register-UI in LibreOffice 7.1 (hidden menu bar) and start a maximized LO-Window, I get an empty black bar instead of the menu bar. 
![LO_black bar](https://user-images.githubusercontent.com/8224416/113263394-ffa8ba00-92d1-11eb-8be4-e9f011974ec7.png)
This doesn't happen every time. If the opening process takes longer (large document or slow computer) this issue doesn't appear. It seems to be a timing problem. This might not be something you can fix, but since LO is a very common application this might bother more people.

**Comment by LostinSpacetime** [comment] 2021-04-01 08:16
I am getting this behavior on two different systems:
1. Intel Laptop running Ubuntu 20.04
2. All AMD Desktop running Ubuntu 20.10

**Comment by Leleat** [comment] 2021-04-28 15:39
IIRC I had similiar issues with other apps(?) but only on Wayland...

**Comment by LostinSpacetime** [comment] 2021-05-06 05:10
I'm using X not Wayland.

**Comment by jonian** [comment] 2021-09-15 18:41
Closing as I can't reproduce this and even if I could, there is no way to fix it. Maybe report it upstream to mutter.

**Closed by jonian** 2021-09-15 18:41 UTC
