### ISSUE TITLE
Right-click on tray icons does not open context menu

### ISSUE THREAD

**Issue by flortsch** [hardpixel/unite-shell#73] opened 2018-11-27 15:37 UTC
Running the latest release of Unite in Gnome Shell 3.30.2 on Wayland.
Right-clicking on an icon in the tray (e.g. on telegram-desktop) does not open the context menu.
However, it works in an x11 session.

**Comment by IgorHordiichuk** [comment] 2018-11-28 22:58
Actually, the icons are clickable at the bottom only. On Xorg works great.

**Comment by flortsch** [comment] 2018-11-28 23:06
Yeah, now that you mention it, I tried it and it's the same for me. So clicking at the top and bottom edge of the bar where the tray icon is works, but not in the middle of the icon.

**Comment by jonian** [comment] 2018-12-01 17:36
I tried to fix this with multiple methods but nothing worked in a consistent way with all the icons:

**1. Add overlay button**
Adding a transparent button over the icon does not change anything.

**2. Add a delay before showing the icon (on icon added)**
With 500ms - 1000ms delay, before showing the icon, some applications worked (qbittorrent, slack) and some worked only on the first click (telegram, megasync).  

Also there was a weird bahavior when a non working icon was clicked multiple times (megasync) and then a working icon was clicked (qbittorent), the dropdown shown was from the non working icon (megasync). 

**3. Toggle icon visibility on every click (no delay)**
Using the delay on icon added to get the first click working, then I added an instant toggle of the `visible` attribute. This worked, but the icon de-saturation was toggled on every click.

**4. Toggle icon visibility on every click (with delay)**
Doing the same as in 3 with a delay of 200ms, all buttons worked without problems, but it was very annoying to see the icon hide/show on every click and I do not think this is an acceptable solution.

So I'm marking this as help-wanted, if anyone wants to try and fix it.

**Comment by IgorHordiichuk** [comment] 2018-12-01 19:08
Looks like that is a Wayland bug. I tried another one extension and it has this bug too, the only difference is that it works one time and then tray icons area is active only at top & bottom. There is an issue report about this bug https://github.com/phocean/TopIcons-plus/issues/83

**Comment by jonian** [comment] 2019-10-03 08:40
This is fixed on Gnome Shell 3.34. Not a bug of this extension.

**Closed by jonian** 2019-10-03 08:40 UTC
Labels: invalid
