### ISSUE TITLE
option to restore window icon

### ISSUE THREAD

**Issue by aperomsik** [hardpixel/unite-shell#69] opened 2018-11-11 00:27 UTC
This extension gets many things right. However the first thing I noticed when enabling it is that the icon for the active window disappeared. Might be nice to have an option to keep it.

**Comment by jonian** [comment] 2018-12-02 00:53
Hi @aperomsik, thank you for your input. This if part of issue #43, so I'm marking it as duplicate of #43.

**Closed by jonian** 2018-12-02 00:53 UTC
