### ISSUE TITLE
[Feature Request] Default ambiance buttons

### ISSUE THREAD

**Issue by Advisord** [hardpixel/unite-shell#22] opened 2017-11-01 18:34 UTC
It would be nice to have a default ambiance theme window buttons at the top left corner instead of custom ones

**Comment by olibia** [comment] 2017-11-01 20:04
Hello @Advisord, thanks for you input.

We will provide options for the icon themes on a later version, it is on our roadmap.

I'm closing this issue because it is a duplicate of #10.

**Closed by olibia** 2017-11-01 20:04 UTC
